FROM centos:centos8

ARG MAJOR_VERSION=5.0
ARG ZBX_VERSION=${MAJOR_VERSION}.19
ARG ZBX_SOURCES=https://git.zabbix.com/scm/zbx/zabbix.git

ENV TERM=xterm \
    ZBX_VERSION=${ZBX_VERSION} ZBX_SOURCES=${ZBX_SOURCES} \
    MIBDIRS=/usr/share/snmp/mibs:/var/lib/zabbix/mibs MIBS=+ALL \
    ZBX_SNMP_TRAP_DATE_FORMAT=+%Y%m%d.%H%M%S ZBX_SNMP_TRAP_FORMAT=" "

LABEL org.opencontainers.image.authors="Alexey Pustovalov <alexey.pustovalov@zabbix.com>" \
      org.opencontainers.image.description="Zabbix SNMP traps receiver" \
      org.opencontainers.image.documentation="https://www.zabbix.com/documentation/${MAJOR_VERSION}/manual/installation/containers" \
      org.opencontainers.image.licenses="GPL v2.0" \
      org.opencontainers.image.title="zabbix-snmptraps" \
      org.opencontainers.image.url="https://zabbix.com/" \
      org.opencontainers.image.vendor="Zabbix LLC" \
      org.opencontainers.image.version="${ZBX_VERSION}"

STOPSIGNAL SIGTERM

COPY CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo
COPY CentOS-AppStream.repo /etc/yum.repos.d/CentOS-AppStream.repo
COPY zabbix_trap_receiver.pl /usr/bin/zabbix_trap_receiver.pl
RUN set -eux && \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    rm -rf /etc/yum.repos.d/CentOS-Linux-* && \ 
    yum clean all && \
    yum makecache && \
    rpm -ivh http://repo.okay.com.mx/centos/8/x86_64/release/okay-release-1-3.el8.noarch.rpm && \
    dnf install -y 'dnf-command(config-manager)' && \
    dnf install -y centos-release-stream && \
    dnf config-manager --set-enabled PowerTools

RUN set -eux && \
    REPOLIST="BaseOS,AppStream" && \
    INSTALL_PKGS="bash \
            tzdata \
            wget \
            net-snmp-utils \
            net-snmp-perl \
            perl(SNMP) \
            perl(XML::Simple) \
            net-snmp \
            perl-Sys-Syslog \
            perl-DBD-MySQL"  && \ 
    dnf -y install \
            --disablerepo "*" \
            --enablerepo "${REPOLIST}" \
            --setopt=tsflags=nodocs \
            --setopt=install_weak_deps=False \
            --best \
        ${INSTALL_PKGS} && \
    groupadd \
            --system \
            --gid 1995 \
        zabbix && \
    useradd \
            --system \
            --comment "Zabbix monitoring system" \
            -g zabbix \
            -G root \
            --uid 1997 \
            --shell /sbin/nologin \
            --home-dir /var/lib/zabbix/ \
        zabbix && \
    mkdir -p /var/lib/zabbix && \
    mkdir -p /var/lib/zabbix/snmptraps && \
    mkdir -p /var/lib/zabbix/mibs && \
    touch /var/lib/net-snmp/snmptrapd.conf && \
    chown --quiet -R zabbix:root /etc/snmp/ /var/lib/zabbix/ /var/tmp/ /var/run/ && \
    chgrp -R 0 /etc/snmp/ /var/lib/zabbix/ /var/tmp/ /var/run/ && \
    chmod -R g=u /etc/snmp/ /var/lib/zabbix/ /var/tmp/ /var/run/ && \
    dnf -y clean all && \
    rm -rf /var/cache/yum /var/lib/yum/yumdb/* /usr/lib/udev/hwdb.d/* && \
    rm -rf /var/cache/dnf /etc/udev/hwdb.bin /root/.pki


COPY snmptt/snmptt /usr/sbin/
COPY snmptt.conf  /etc/snmp/snmptt.conf
COPY snmptthandler /usr/sbin/
COPY snmptt.ini /etc/snmp/
RUN set -eux && \
   chmod +x /usr/sbin/snmptt && \
   chmod +x /usr/sbin/snmptthandler && \
   echo 'OPTIONS="-m +ALL -On"' >> /etc/sysconfig/snmptrapd && \
   mkdir -p /var/log/snmptt/ && \
   more /etc/sysconfig/snmptrapd 

EXPOSE 1162/UDP

WORKDIR /var/lib/zabbix/snmptraps/

VOLUME ["/var/lib/zabbix/snmptraps"]

COPY ["conf/etc/logrotate.d/zabbix_snmptraps", "/etc/logrotate.d/"]
COPY ["conf/etc/snmp/snmptrapd.conf", "/etc/snmp/"]
COPY ["conf/usr/sbin/zabbix_trap_handler.sh", "/usr/sbin/"]

USER 1997

CMD ["/usr/sbin/snmptrapd", "-On", "-n", "-C", "-c", "/etc/snmp/snmptrapd.conf", "-Lo", "-A"]
